/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "CryptoGifts",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CryptoGifts__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "Payable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Payable__factory>;
    getContractFactory(
      name: "CryptoGifts",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CryptoGifts__factory>;
    getContractFactory(
      name: "ICryptoGifts",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ICryptoGifts__factory>;
    getContractFactory(
      name: "Greeter",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Greeter__factory>;
    getContractFactory(
      name: "Payable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Payable__factory>;

    getContractAt(
      name: "Ownable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "CryptoGifts",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CryptoGifts>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;
    getContractAt(
      name: "Payable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Payable>;
    getContractAt(
      name: "CryptoGifts",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.CryptoGifts>;
    getContractAt(
      name: "ICryptoGifts",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ICryptoGifts>;
    getContractAt(
      name: "Greeter",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Greeter>;
    getContractAt(
      name: "Payable",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Payable>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
