name: Functions
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - packages/functions/**
      - packages/ethereum/**
      - .github/workflows/functions.yml

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
      ROPSTEN_URL: ${{ secrets.ROPSTEN_URL }}
      KOVAN_URL: ${{ secrets.KOVAN_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node-pnpm-cache
      - run: pnpm ethereum:compile
      - run: pnpm functions:build
      - if: ((github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && !startsWith(github.head_ref,'renovate')))
        run: pnpm functions:deploy
