name: Hosting
on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - packages/app/**
      - packages/ethereum/**
      - .github/workflows/hosting.yml

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      RINKEBY_URL: ${{ secrets.RINKEBY_URL }}
      ROPSTEN_URL: ${{ secrets.ROPSTEN_URL }}
      KOVAN_URL: ${{ secrets.KOVAN_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-node-pnpm-cache
      - run: pnpm ethereum:compile
      - run: pnpm app:build
      - uses: actions/upload-artifact@v2
        with:
          name: app
          path: |
            packages/app/build
            firebase.json
            .firebaserc
  deploy:
    needs: build
    if: ((github.ref == 'refs/heads/main') || (github.event_name == 'pull_request' && !startsWith(github.head_ref,'renovate')))
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: app
      - run: pnpm app:deploy
